// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    GalleryPopup: typeof import('./components/GalleryPopup.vue')['default']
    HeaderMenuItem: typeof import('./components/HeaderMenuItem.vue')['default']
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    Logo: typeof import('./components/svg/Logo.vue')['default']
    PageButton: typeof import('./components/PageButton.vue')['default']
    PageContainer: typeof import('./components/PageContainer.vue')['default']
    PagePopup: typeof import('./components/PagePopup.vue')['default']
    PriceListGroup: typeof import('./components/PriceListGroup.vue')['default']
    SectionTitle: typeof import('./components/SectionTitle.vue')['default']
    TeamEmployeeBadge: typeof import('./components/TeamEmployeeBadge.vue')['default']
  }
}

export { }
